-- Staff passwords are generated by us and delivered over a channel we do not
-- control (chat, email). Forcing a change on first sign-in means the delivered
-- secret stops working once the admin is in. Set on account creation and on
-- every password reset; cleared when the admin chooses their own password.
ALTER TABLE users ADD COLUMN must_change_password boolean NOT NULL DEFAULT false;

-- Existing staff rows predate the flag; they keep their current passwords
-- rather than being locked out of a console they already use.

-- Admin-declared wants get an optional quantity so the public page can say
-- "5 torches needed" rather than just naming the category. NULL means "we need
-- this, amount unspecified" — a deliberate distinct state, not zero.
ALTER TABLE event_admin_wants ADD COLUMN qty integer;

ALTER TABLE event_admin_wants
  ADD CONSTRAINT event_admin_wants_qty_sane CHECK (qty IS NULL OR (qty > 0 AND qty <= 1000000));
